/**
 * Builds the offline PDF surface: pdf.js (legacy build, for older WebViews) + its worker + the
 * surface code, inlined into one HTML file at assets/pdf-surface/surface.html.
 *
 *   npm run build:surface          # write the file
 *   npm run build:surface -- --check   # fail if the committed file is stale (CI / tests)
 */
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const out = join(root, 'assets/pdf-surface/surface.html');

const target = ['es2020', 'safari15', 'chrome90'];

// The worker is bundled as a classic script: module workers fail in opaque origins (file:// pages in
// WebViews, sandboxed iframes). `globalName` also lets the surface run it on the main thread as a
// fallback, where pdf.js picks it up from `globalThis.pdfjsWorker`.
const worker = await build({
  entryPoints: [require.resolve('pdfjs-dist/legacy/build/pdf.worker.mjs')],
  bundle: true,
  format: 'iife',
  globalName: 'pdfjsWorker',
  target,
  minify: true,
  legalComments: 'none',
  write: false,
  // Only used to locate optional wasm decoders, which are not bundled (see README).
  define: { 'import.meta.url': 'self.location.href' },
  logLevel: 'warning',
});
const workerSrc = worker.outputFiles[0].text;

const result = await build({
  entryPoints: [join(root, 'web/pdf-surface/src/main.ts')],
  bundle: true,
  format: 'iife',
  target,
  minify: true,
  legalComments: 'none',
  write: false,
  define: { __PDF_WORKER_SRC__: JSON.stringify(workerSrc) },
  logLevel: 'warning',
});

const script = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const template = readFileSync(join(root, 'web/pdf-surface/template.html'), 'utf8');
const html =
  '<!-- GENERATED by scripts/build-surface.mjs from web/pdf-surface — do not edit. -->\n' +
  template.replace('/*__SURFACE_SCRIPT__*/', () => script);

if (process.argv.includes('--check')) {
  const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (current !== html) {
    console.error('assets/pdf-surface/surface.html is stale: run `npm run build:surface`.');
    process.exit(1);
  }
  console.log('surface.html is up to date');
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, html);
  console.log(`wrote ${out} (${(html.length / 1024).toFixed(0)} KB)`);
}
